### ISSUE TITLE
Implementation of deployment progress in deployment status API call

### ISSUE THREAD

**Issue by kmlTE** [SODALITE-EU/xopera-rest-api#90]
# Current state
Currently, there is no way to track a deployment progress in a convenient way, e.g. by showing the percentages of the progress (75%) or deployment fractions (16/20).

# Desired state
The deployment status (/deployment/{deployment_id}/status) should also provide a deployment progress, e.g. by showing in a general way the total number of nodes in node_templates and how many nodes were deployed so far:
```json
{
  "blueprint_id": "uuid-1",
  "deployment_id": "uuid-2",
  "instance_state": {...},
  "operation": "deploy_fresh",
  "state": "in_progress",
  "stderr": "",
  "stdout": "",
  "timestamp": "2021-03-22T19:47:50.715611+00:00",
  "version_id": "v1.0",
  "workers": 1,
  "total_nodes_num": 20, // the naming can be improved
  "current_nodes_num": 16 // the naming can be improved
}
```

**Comment by mihaTrajbaric** [comment]
https://github.com/SODALITE-EU/xopera-rest-api/pull/95 seems sufficient, I will close this issue.
